site_name: Abylay's Site
site_url: https://almaty-itrider.github.io/about_me/
theme:
  name: material
site_author: Abylay Kuvatov
copyright: Abylay Kuvatov, itrider, 2024
plugins:
  - search
  - i18n:
      docs_structure: folder
      languages:
        - locale: en
          default: true
          name: English
          build: true
        - locale: ru
          name: Russian
          build: true
        - locale: kk
          name: Kazakh
          build: true
