site_name: Abylai's Site
site_url: https://almaty-itrider.github.io/about_me/
theme:
  name: material
site_author: Abylai Kuvatov
copyright: Abylai Kuvatov, itrider, 2024
plugins:
  - search
  - i18n:
      default_language: en
      languages:
        en: 
          name: English
          locale: en_US
        ru: 
          name: Russian
          locale: ru_RU
        kk: 
          name: Kazakh
          locale: kk_KZ
      docs_structure: folder
